name: CI

on:
  pull_request:
    branches:
      - main
      - dev/**
      - release/**

jobs:
  test:
    name: Run tests with Testcontainers
    runs-on: ubuntu-latest  # Docker included

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Start Docker (needed by Testcontainers)
        run: |
          sudo systemctl start docker
          docker info

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon
