name: CI

on:
  pull_request:
    branches:
      - main
      - dev/**
      - release/**

  push:
    branches:
      - main
      - dev/**
      - release/**

jobs:
  test:
    name: Run tests with Testcontainers
    runs-on: ubuntu-latest  # Docker included

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Start Docker (richiesto da Testcontainers)
        run: |
          sudo systemctl start docker
          docker info

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon
